# Generated by Django 5.1.5 on 2025-02-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_links_alter_about_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='git_hub',
        ),
        migrations.RemoveField(
            model_name='links',
            name='linkdin',
        ),
        migrations.AddField(
            model_name='links',
            name='link',
            field=models.URLField(default='https://example.com', max_length=100),
        ),
        migrations.AddField(
            model_name='links',
            name='platform',
            field=models.CharField(default='https://example.com', max_length=25),
            preserve_default=False,
        ),
    ]
